dist: trusty
sudo: required
language: node_js
node_js:
- '6.9.1'
os:
- linux
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
before_script:
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run lint
- npm run test-once
cache:
  bundler: true
  directories:
  - node_modules
deploy:
    provider: s3
    access_key_id: 'AKIAITVMCHIKP4YOGVHQ'
    bucket: "talent-highway"
    skip_cleanup: true
    secret_access_key:
      secure: vPN3ruoYHe6xiiSa2kxHfiuwYxYRhyJlRGfRF7RTDN0B0ve0SnMC5uwKDnJkfpBS7YxVvtSA9STJMRLs6MLimbiNU5DmNVSN8fzgCruTUNkxdcdKv9nNMFOmQoGI0YZh8epFLarOgLdLdHgumzPxUSWM4JgxwewAP/HD0rkXlG6quHkGS4d/+cESqePYPxYSoVTtoF9lxfWze5AKJ0xBYMrcd0Dv1oBwbSuKs/CJ9tSbqy3gmfSw2E2Zv5qH8OFrFK2un2xzLDB2oFCi8vt1FaISdc6m/WqJRtEAeCqc+hPZCuwuoWUOMh6ZdcFr1NnMmI91Zmh2inuxnUPgPdREqX4xlpkOwi9pdcTwnDKsnW+xNAWV8VEJRbv5Ac8B14QmrJXlM8bT+rjDmW9IPyOPh3cQOnPwnbvevx3TPHFOddEXjS3X+oAsNkhKGytcVVE6v1l2gK6M9uBMpsqhqmpazO/7VZ9If6h1ClOUmrVf8chzQH45wSN74w07E7FLVu0VfWVJ3TV72v7iTKf5zw3ViqSx9/MsX9X6nyZhMyhnagO4OdVO63RLkGxca3FScUoxOrwbgaOmZYfkrOkOjJ72l78Wi/nCsoIfQAwNV/CuiOjZUIxHbGTrOq4xw+4pDLgHIKzAV/ifMAZ2rFIOx+ApXUNS1cHjbGmimWQAZ4PTOvA=
